# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: DarkAlexWang's Blog
subtitle:
description: Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.
author: darkalexwang
language: en 
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: darkalexwang.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: [README.md, ori_data/*, ori_data/posts/*, ori_data/tags/*, ori_data/categories/*, ori_data/themes/next/*] # 禁止进行渲染的文件

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next-reloaded
word_count: true

# Avatar
#avatar: https://c2.staticflickr.com/8/7464/27053268555_c92b86047e_o.jpg

search:
  path: search.xml
  field: post
  format: html
  limit: 10000


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:DarkAlexWang/darkalexwang.github.io.git 
  branch: master

# Social links
#social:
  #GitHub: https://www.github.com/DarkAlexWang
  #Linkedin: https://www.linkedin.com/in/zhihuan-wang
  #微博: http://www.weibo.com/youhusky
  #豆瓣: https://www.douban.com/people/1098945/
  #知乎: http://www.zhihu.com/people/Joshua_husky

sitemap:
  path: sitemap.xml
# baidusitemap:
  # path: baidusitemap.xml

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: false

# Security
encrypt:
  enable: true

# offline config passed to sw-precache.
service_worker:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs:
  - public/about/index.html
  - public/favicon.ico
  - public/manifest.json
  stripPrefix: public
  verbose: false
  runtimeCaching:
    - urlPattern: /**/*
      handler: cacheFirst
      options:
        origin: darkalexwang.github.io

#filter_optimize:
#  enable: true
#  # remove static resource query string
#  #   - like `?v=1.0.0`
#  remove_query_string: true
#  # remove the surrounding comments in each of the bundled files
#  remove_comments: false
#  css:
#    enable: false
#    # bundle loaded css file into the one
#    bundle: true
#    # use a script block to load css elements dynamically
#    delivery: true
#    # make specific css content inline into the html page
#    #   - only support the full path
#    #   - default is ['css/main.css']
#    inlines:
#    excludes:
#  js:
#    # bundle loaded js file into the one
#    bundle: true
#    excludes:
#  # set the priority of this plugin,
#  # lower means it will be executed first, default is 10
#  priority: 12
# 
#fontawesome: //cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
